# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [2]:

  import numpy as np

#### 1) Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Print the memory size in bytes of any array (★☆☆)

In [5]:
Z = np.zeros((10,10))
memory_size = Z.nbytes
print(f"Memory size: {memory_size} bytes")


Memory size: 800 bytes


#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
Z = np.zeros(10)
Z[4] = 1
print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4) Create a vector with values ranging from 20 to 80 (★☆☆)

In [10]:
vector = np.arange(20, 81)
print(vector)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80]


#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [11]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
values = np.arange(9)
matrix = values.reshape((3, 3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [13]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 8) Create a 3x3 identity matrix (★☆☆)

In [14]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 9) Create a 3x3x3 array with random values (★☆☆)

In [15]:
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.99559661 0.0286654  0.74895719]
  [0.25422825 0.64476584 0.45710438]
  [0.60539633 0.72133007 0.86699717]]

 [[0.23870074 0.49219621 0.93869308]
  [0.98588046 0.25969596 0.80198231]
  [0.58652836 0.80889325 0.05982404]]

 [[0.22336136 0.41769421 0.28606584]
  [0.31222673 0.72650703 0.31546268]
  [0.9561407  0.06169873 0.44791138]]]


#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:

array = np.random.rand(10, 10)
minimum = array.min()
maximum = array.max()

print("Array:")
print(array)
print("\nMinimum value:", minimum)
print("Maximum value:", maximum)

Array:
[[0.75116402 0.73812039 0.18255042 0.13061332 0.35566237 0.79113786
  0.11383825 0.51839601 0.67354152 0.2089363 ]
 [0.65153331 0.35914797 0.90787344 0.02312591 0.5476491  0.33752273
  0.86596149 0.45008019 0.47990087 0.46147006]
 [0.44194937 0.51500577 0.51420117 0.6594006  0.03266925 0.53985942
  0.26888468 0.78781608 0.10879972 0.6130886 ]
 [0.47092254 0.36820143 0.02727283 0.93320235 0.15628427 0.32556774
  0.03814476 0.93990726 0.5027538  0.00792923]
 [0.38975474 0.89945973 0.50697903 0.75649851 0.35361047 0.10478421
  0.54369767 0.96519115 0.38937986 0.81626808]
 [0.60872122 0.19148407 0.37416645 0.79752562 0.58546962 0.53424362
  0.14671653 0.28499946 0.2945862  0.83209553]
 [0.79150419 0.66908434 0.83456768 0.1088164  0.44512072 0.2503434
  0.54075081 0.1575874  0.79024837 0.88228437]
 [0.2362354  0.15287096 0.15488003 0.14959895 0.0469861  0.68065206
  0.26071085 0.16508861 0.6199422  0.91894772]
 [0.15537664 0.0446414  0.66762301 0.00466307 0.41444248 0.19578622
  0.86

#### 11) Create a random vector of size 30 and find the mean, variance values (★☆☆)

In [17]:
vector = np.random.rand(30)
mean = np.mean(vector)
variance = np.var(vector)

print("Random Vector:")
print(vector)
print("\nMean:", mean)
print("Variance:", variance)

Random Vector:
[0.64799493 0.26551193 0.45516655 0.82592892 0.6159588  0.81428266
 0.50178888 0.8147406  0.96641141 0.00823391 0.19105152 0.83683054
 0.39167291 0.34829875 0.66727949 0.46680449 0.29233393 0.14590313
 0.15339324 0.1635089  0.08041684 0.59477959 0.22306179 0.84488994
 0.3869626  0.53884898 0.35730537 0.03467043 0.50909628 0.86421741]

Mean: 0.46691149129568194
Variance: 0.07540475232845792


#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
Z = np.ones((10,10))
array[1:-1, 1:-1] = 0
print(array)

[[0.75116402 0.73812039 0.18255042 0.13061332 0.35566237 0.79113786
  0.11383825 0.51839601 0.67354152 0.2089363 ]
 [0.65153331 0.         0.         0.         0.         0.
  0.         0.         0.         0.46147006]
 [0.44194937 0.         0.         0.         0.         0.
  0.         0.         0.         0.6130886 ]
 [0.47092254 0.         0.         0.         0.         0.
  0.         0.         0.         0.00792923]
 [0.38975474 0.         0.         0.         0.         0.
  0.         0.         0.         0.81626808]
 [0.60872122 0.         0.         0.         0.         0.
  0.         0.         0.         0.83209553]
 [0.79150419 0.         0.         0.         0.         0.
  0.         0.         0.         0.88228437]
 [0.2362354  0.         0.         0.         0.         0.
  0.         0.         0.         0.91894772]
 [0.15537664 0.         0.         0.         0.         0.
  0.         0.         0.         0.81305313]
 [0.4293712  0.60924379 0.731

#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 14) Predict (before executing) the results of the following expressions? (★☆☆)

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 15) Create a 6×6 matrix with values 1,2,3,4,5 just below the diagonal (★☆☆)

In [20]:
matrix = np.diag(np.arange(1, 6), k=-1)
print(matrix)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [21]:
Z = np.zeros((8,8),dtype=int)
Z[::2, 1::2] = 1
Z[1::2, ::2] = 1
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 17) Consider a (5,6,7) shape array, what is the index (x, y, z) of the 50th element?

In [22]:
arr = np.arange(5 * 6 * 7).reshape(5, 6, 7)
index = np.unravel_index(49, arr.shape)
print(index)

(np.int64(1), np.int64(1), np.int64(0))


#### 18) Multiply a 4x2 matrix by a 2x3 matrix (real matrix product) (★☆☆)

In [23]:
matrix1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
matrix2 = np.array([[9, 10, 11], [12, 13, 14]])

result = np.dot(matrix1, matrix2)
print(result)

[[ 33  36  39]
 [ 75  82  89]
 [117 128 139]
 [159 174 189]]


#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 20. How to find common values between two arrays? (★☆☆)

In [26]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


[3 4 5 8 9]


#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [25]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

#### 22) Extract the integer part of a random array (★★☆)

In [28]:
Z = np.random.uniform(0,10,10)
Z_int = Z.astype(int)
print(Z_int)

[0 7 1 2 0 0 1 4 7 2]


#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [29]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [30]:
def generate_integers():
    for i in range(10):
        yield i

Z = np.fromiter(generate_integers(), dtype=int)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [31]:
v = np.linspace(0,1,12,endpoint=True)[1:-1]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26) Create a random vector of size 10 and sort it (★★☆)

In [32]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.0177488  0.04877095 0.20297877 0.22819863 0.32253238 0.4595694
 0.71914041 0.76219555 0.80547967 0.84988704]


#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [33]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)



False


#### 28) Make an array immutable (read-only) (★★☆)

In [35]:
Z = np.zeros(10)
Z.flags.writeable = False


#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [36]:
Z = np.random.random(10)#
Z[Z.argmax()] = 0
print(Z)

[0.13762239 0.78863254 0.38443342 0.45252604 0.7991761  0.
 0.92039282 0.34810832 0.90052891 0.9119018 ]


#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [37]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)


[0 1 2 3 4 5 6 7 8 9]


#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [38]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 32) Subtract the mean of each row of a matrix (★★☆)

In [39]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.21578729  0.21634752 -0.34287304  0.44722291  0.53416757 -0.09008852
   0.45155619 -0.3631375  -0.2849295  -0.35247833]
 [-0.12294328  0.01329666 -0.00285713  0.34210245  0.09623397 -0.16252354
  -0.21099888  0.37085642 -0.41527743  0.09211074]
 [ 0.33491835  0.16289254 -0.32534239 -0.1822551   0.39361215  0.3599821
  -0.35098919  0.38444537 -0.35348408 -0.42377976]
 [-0.18850852 -0.24315511  0.04624602 -0.28197464 -0.36570325  0.51653594
  -0.31530114  0.50849046  0.34822559 -0.02485535]
 [-0.08339646 -0.02064039 -0.11518864 -0.24267331  0.63372156 -0.2062783
  -0.25075625 -0.00102496 -0.19440109  0.48063785]]


#### 33) sort an array by the 1st column? (★★☆)

In [41]:
Z = np.random.randint(0,10,(3,3))
print(Z[Z[:,0].argsort()])

[[1 2 9]
 [4 8 8]
 [6 6 6]]


#### 34) Find the nearest value from a given value z in an array Z(★★☆)

In [42]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.40764446123605147


#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [43]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 36) find the most frequent value in an array

In [44]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


7


#### 37) Given a two dimensional array, extract unique rows (★★★)

In [45]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
