# Recalling Numpy Array Slicing and Indexing

In [3]:
import numpy as np

In [4]:
#create array
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [5]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

## Slice first 3 elements

<img src="IMG/np01.png">

##  Slice first 8 elements

<img src="IMG/np02.png">

## Skip every other element

<img src="IMG/np03.png">

## Slice first column

<img src="IMG/np04.png">

## Slice a diagonal

<img src="IMG/np05.png">

## Repeat the first element

<img src="IMG/np06.png">

## Simple 2D slicing

<img src="IMG/np07.png">

## Slice a zigzag 

<img src="IMG/np08.png">

## Sparse slicing

<img src="IMG/np09.png">

## Transpose a 2D array

<img src="IMG/np10.png">

## Repeat the first column 4 times


<img src="IMG/np11.png">

## Reshape 1D array to 2D array

<img src="IMG/np12.png">

In [9]:
x = np.asarray(range(1,13), np.int64)
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Collapse an axis from a 3D array

<img src="IMG/np13.png">

In [8]:
x = np.asarray(range(1,13), np.int8).reshape(3,2,2)
print(x)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
